apiVersion: v1
kind: Pod
metadata:
  name: mypod-lb
  labels:
    app: myapp-lb
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myservicelb
spec:
  selector:
    app: myapp-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
