apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: deploy-tomcat
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deploy-tomcat
  template:
    metadata:
      labels:
        app: deploy-tomcat
    spec: 
      containers:
      - name: tomcat-containers
        image: tomcat:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: 
          requests:
            memory: "64Mi"
            cpu: "120m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-hpa
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
