version: "3.8"
services: 
  todo-app:
    build:
      context: .
    container_name: todo-app-container
    ports: 
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - myvol:/var/lib

volumes:
  myvol:
networks:
  mynetwork:
    