apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: pv-vol
  labels:
    app: pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/"
