apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: pv-claim
spec: 
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3Gi